add button
js-tasks-ru/vue-20201210_eg-nosach pull request #2
Opened 2020-12-16 15:28 UTC by egor3333

2020-12-16 16:11 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-12-16 17:58 UTC, ShGKme requested changes
Первая задача принята, но требуется решить все добавленные задачи, чтобы PR был принят

2020-12-16 22:45 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 01-basics/02-MeetupPageDraft/__tests__/MeetupPageDraft.test.js — добавлен
```

2020-12-17 00:04 UTC, ShGKme requested changes
Требуется установить начальным значением данных митапа `null` ит добавить проверки:
- В вычисляемое свойство
- В шаблон v-if, чтобы не выводить страницу с данными митапа, пока не пришли данные митапа

В остальном всё отлично

2020-12-17 00:04 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +    rawMeetup: {}
На вебинаре мы начальным значением массива устанавливали пустой массив. Это корректно, пустой массив митапов - это частный случай массива митапов. Но пустой объект - не частный случай объекта с описанием митапа. Хотя установка начального значения в {} избавляет от простых ошибок, она не избавляет от ошибок полностью, оставляя более трудно-находимые ошибки. Лучше начальным значением указать null и делать проверки. Например, сейчас на время загрузки митапа отображается "сломанная" страница с пустыми значениями.

2020-12-17 09:38 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 01-basics/02-MeetupPageDraft/__tests__/MeetupPageDraft.test.js — добавлен
```

2020-12-17 09:50 UTC, egor3333 commented
Заметил что `v-cloak` почему-то не работает, видна страница шаблона

2020-12-17 11:37 UTC, ShGKme approved these changes
Принято 👍

2020-12-17 11:38 UTC, merged

2020-12-17 11:43 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +  </style>
Здесь опечатка, из-за которой не работает `v-cloak`, двоиточие лишнее после селектора по атрибутам.

2020-12-17 11:44 UTC, egor3333 commented on 01-basics/02-MeetupPageDraft/index.html
> +  </style>
Спасибо)